# Generated by Django 4.0.1 on 2022-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=5)),
                ("path", models.CharField(max_length=50000)),
                ("status", models.IntegerField(default=0)),
                ("duration", models.CharField(max_length=15)),
                ("payload", models.JSONField()),
                ("header", models.JSONField()),
                ("responses", models.JSONField()),
                ("happened", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
