# Generated by Django 4.0.1 on 2022-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdb',
            name='payload',
            field=models.JSONField(blank=True),
        ),
    ]
